#pragma once

enum class TileSignal {
    NONE,
    BLOCK_BULLET,
    DESTROY_BULLET,
    DESTROY_TILE,
    MOVE_TILE,
    MOVE_TILE_RIGHT,
    MOVE_TILE_LEFT,
    MOVE_TILE_UP,
    MOVE_TILE_DOWN,
    REFLECT_UP,
    REFLECT_DOWN,
    REFLECT_LEFT,
    REFLECT_RIGHT,
    DESTROY_TANK_UP,
    DESTROY_TANK_DOWN,
    DESTROY_TANK_RIGHT,
    DESTROY_TANK_LEFT
};
